name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Pull from Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t nicvalencia/city-orlando-permit .
      - name: Publish Image to Docker Hub
        run: docker push nicvalencia/city-orlando-permit:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull nicvalencia/city-orlando-permit:latest
      - name: Remove Old Container
        run: docker rm -f city-orlando-permit-container
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name city-orlando-permit-container nicvalencia/city-orlando-permit:latest


